# Softmax classifier


---

### 1. 학습 데이터

In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('lab6_data.txt',unpack=True,dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

print('x_data : \n',x_data)
print('--------------')
print('y_data \n: ',y_data)

x_data : 
 [[ 1.  2.  1.]
 [ 1.  3.  2.]
 [ 1.  3.  4.]
 [ 1.  5.  5.]
 [ 1.  7.  5.]
 [ 1.  2.  5.]
 [ 1.  6.  6.]
 [ 1.  7.  7.]]
--------------
y_data 
:  [[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


### 2. variable

In [2]:
X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])
W = tf.Variable(tf.zeros([3,3]))

### 3. Hypothesis

In [3]:
hypothesis = tf.nn.softmax(tf.matmul(X,W))

### 4. cost함수 - 크로스엔트로피

In [4]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),reduction_indices=1))

### 5. minimise cost - 경사하강법

In [5]:
learning_rate = 0.001
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

### 6. 초기화

In [6]:
init = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


### 7. 학습 실행

In [7]:
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data,Y:y_data})
        if step % 200 == 0:
            print(step,' cost: ',sess.run(cost,feed_dict={X:x_data,Y:y_data}),'\n',sess.run(W))
            
    # 검증
    a = sess.run(hypothesis, feed_dict={X:[[1,11,7]]})
    print(a,sess.run(tf.arg_max(a,1)))

    b = sess.run(hypothesis, feed_dict={X:[[1,3,4]]})
    print(b,sess.run(tf.arg_max(b,1)))

    c = sess.run(hypothesis, feed_dict={X:[[1,1,0]]})
    print(c,sess.run(tf.arg_max(c,1)))

    all = sess.run(hypothesis, feed_dict={X:[[1,11,7],[1,3,4],[1,1,0]]})
    print(all,sess.run(tf.arg_max(all,1)))

0  cost:  1.09774 
 [[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
200  cost:  1.05962 
 [[-0.02051384 -0.00103983  0.02155367]
 [ 0.01406438  0.01097753 -0.02504191]
 [ 0.01431208  0.03574873 -0.05006079]]
400  cost:  1.04985 
 [[-0.04282598 -0.00625899  0.04908497]
 [ 0.01747187  0.00156368 -0.01903554]
 [ 0.01831204  0.04954104 -0.06785304]]
600  cost:  1.0407 
 [[-0.06517859 -0.01176361  0.07694222]
 [ 0.01943521 -0.00848972 -0.01094548]
 [ 0.0211558   0.06118308 -0.0823388 ]]
800  cost:  1.03194 
 [[-0.08734013 -0.01729389  0.10463405]
 [ 0.0211172  -0.01796171 -0.00315548]
 [ 0.02396628  0.07198346 -0.09594974]]
1000  cost:  1.02354 
 [[-0.10928574 -0.02282181  0.13210757]
 [ 0.02266254 -0.02678034  0.00411783]
 [ 0.02685853  0.08210357 -0.10896212]]
1200  cost:  1.01547 
 [[-0.13101467 -0.02834092  0.15935561]
 [ 0.02409703 -0.03497621  0.01087923]
 [ 0.029832    0